fixed a bug

diff --git a/.github/workflows/test_integrations.yml b/.github/workflows/test_integrations.yml
--- a/.github/workflows/test_integrations.yml
+++ b/.github/workflows/test_integrations.yml
@@ -1,8 +1,7 @@
-name: Test integrations
+name: Test Integrations
 
 permissions:
   contents: read
-  actions: write
 
 on:
   push:
@@ -16,7 +15,6 @@ on:
 jobs:
   test_integrations:
     runs-on: ubuntu-latest
-
     steps:
     - name: Checkout repository
       uses: actions/checkout@v4
@@ -41,16 +39,17 @@ jobs:
         mp config --marketplace-path . --processes 10 --display-config
         mp test --repository third_party --repository commercial --raise-error-on-violations
 
-    - name: Fail the workflow if tests failed
-      if: steps.test.outcome == 'failure'
-      run: |
-        echo "Integration test step failed. Failing the workflow."
-        exit 1
+    - name: Upload Test Report Artifact
 
-    - name: Upload Markdown Report Artifact
-      if: always()
+      if: steps.test.outcome == 'failure'
       uses: actions/upload-artifact@v4
       with:
         name: test-report-md
         path: ./artifacts/test_report.md
         retention-days: 2
+
+    - name: Fail the workflow if tests failed
+      if: steps.test.outcome == 'failure'
+      run: |
+        echo "Integration test step failed. Failing the workflow."
+        exit 1
